name: Deploy
on:
  push:
    branches:
      - main
    
jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.   # Repo checkout
        uses: actions/checkout@v3
      
      - name: Check Node v            # Node v 확인
        run: node -v
        
      - name: Install dependencies    # 의존 파일 설치
        run: npm install
        
      - name: build
        run: npm run build
        working-directory: ./src
          
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Deploy to xquare
        uses: team-xquare/xquare-deployment-action@master 
        with:
          environment: YOUR_ENVIRONMENT
          access_key: ${{ secrets.ACCESS_KEY }}
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
