name: Deploy
on:
  push:
    branches:
      - main
    
jobs:                                # Job 설정
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.   # Repo checkout
        uses: actions/checkout@v3
      
      - name: Check Node v            # Node v 확인
        run: node -v
        
      - name: Install dependencies    # 의존 파일 설치
        run: npm install
      
      - name: Generate build          # React Build
        run: npm run build
        env:
          CI: ""

      - name: Deploy to xquare
        uses: team-xquare/xquare-deployment-action@master 
        with:
          environment: prod # ------------------------------------ 1
          access_key: ${{ secrets.XQUARE_ACCESS_KEY }} # ---------------- 2
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # --- 3
